# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 03:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва', max_length=200, verbose_name='article_title')),
                ('content', models.TextField(help_text='Змест', verbose_name='article_content')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата публікацыі')),
                ('image', models.ImageField(blank=True, help_text='Карцінка', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='')),
                ('video', models.FileField(blank=True, help_text='Відэа', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/video'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва', max_length=200)),
                ('description', models.TextField(help_text='Апісанне')),
                ('start_date', models.DateTimeField(help_text='Дата пачатку')),
                ('end_date', models.DateTimeField(help_text='Дата канца')),
                ('location', models.CharField(help_text='Адрас', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва', max_length=200, verbose_name='film_name')),
                ('director', models.CharField(help_text='Рэжысёр', max_length=200)),
                ('year', models.PositiveSmallIntegerField(default=None, help_text='Год')),
                ('genres', models.CharField(choices=[('action', 'Баявік'), ('adventure', 'Прыгода'), ('comedy', 'Камедыя'), ('crime', 'Злачынства'), ('drama', 'Драма'), ('epics/historical', 'Эпас / Гістарычны'), ('horror', 'Жахі'), ('musicals', 'Мюзікл'), ('science fiction', 'Навуковая фантастыка'), ('war', 'Ваенны'), ('westerns', 'Вестэрн')], default='', help_text='Жанры', max_length=200)),
                ('video', models.FileField(help_text='Відэа', storage=django.core.files.storage.FileSystemStorage(location='layout/video'), upload_to='')),
                ('length', models.PositiveSmallIntegerField(help_text='Працягласць')),
                ('description', models.TextField(help_text='Апісанне')),
                ('torrent_links', models.URLField(blank=True, help_text='Спасылка на торэнт')),
            ],
        ),
    ]
