# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 00:34
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Article content', verbose_name='Article content')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date', verbose_name='Publication date')),
                ('image', models.ImageField(blank=True, help_text='Image of article when viewing article list on index or news page', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='', verbose_name='Article image')),
                ('video', models.FileField(blank=True, help_text='Відэа', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/video'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='')),
                ('baner_model', models.CharField(choices=[('baner_top', 'верхний банер'), ('baner_right', 'правый банер')], default='', help_text='банер', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва', max_length=200)),
                ('description', models.TextField(help_text='Апісанне')),
                ('start_date', models.DateTimeField(help_text='Дата пачатку')),
                ('end_date', models.DateTimeField(help_text='Дата канца')),
                ('location', models.CharField(help_text='Адрас', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва', max_length=200, verbose_name='film_name')),
                ('name_origin', models.CharField(default='', help_text='Назва арыгінала', max_length=200, verbose_name='film_name_origin')),
                ('director', models.CharField(help_text='Рэжысёр', max_length=200)),
                ('year', models.PositiveSmallIntegerField(default=None, help_text='Год')),
                ('kp_rating', models.FloatField(null=True)),
                ('imdb_rating', models.FloatField(null=True)),
                ('genres', models.CharField(choices=[('action', 'Баявік'), ('adventure', 'Прыгода'), ('comedy', 'Камедыя'), ('crime', 'Злачынства'), ('drama', 'Драма'), ('epics/historical', 'Эпас / Гістарычны'), ('horror', 'Жахі'), ('musicals', 'Мюзікл'), ('science fiction', 'Навуковая фантастыка'), ('war', 'Ваенны'), ('westerns', 'Вестэрн')], default='', help_text='Жанры', max_length=200)),
                ('stars', models.CharField(default='нет Iнфармацыi', help_text='Акцёры', max_length=200)),
                ('video_html', models.TextField(default='', help_text='html-код для проигрывания видео')),
                ('length', models.CharField(default='', help_text='Працягласць', max_length=25)),
                ('image_url', models.URLField(blank=True, help_text='Спасылка на карцiнку')),
                ('description', models.TextField(help_text='Апісанне')),
                ('country', models.CharField(default='', help_text='Краiна', max_length=200)),
                ('torrent_links', models.URLField(blank=True, help_text='Спасылка на торэнт')),
            ],
        ),
    ]
