# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='kp_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='name_origin',
            field=models.CharField(default='Not found', help_text='Назва арыгінала', max_length=200, verbose_name='film_name_origin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='stars',
            field=models.CharField(default='нет инфармацыi', help_text='Акцёры', max_length=200),
        ),
    ]
