# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baner',
            old_name='baner_model',
            new_name='baner',
        ),
    ]
