# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0002_auto_20180115_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='film_genres_autocomplete', blank=True, help_text='Жанры могут включать в себя пробелы', initial='анімэ, баявік, біяграфія, вэстэрн, гістарычны, дакументальны, драма, дэтэктыў, жахі, камедыя, кароткамэтражны, крымінальны, мюзікл, прыгода, серыял, фантастыка', space_delimiter=False, to='KinaKipa.Genre', tree=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_origin',
            field=models.CharField(blank=True, default='', help_text='Назва арыгінала', max_length=200, verbose_name='film_name_origin'),
        ),
    ]
