# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0002_auto_20171211_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name_origin',
            field=models.CharField(default='', help_text='Назва арыгінала', max_length=200, verbose_name='film_name_origin'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.CharField(default='нет Iнфармацыi', help_text='Акцёры', max_length=200),
        ),
    ]
