# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 20:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0003_auto_20171212_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='')),
                ('baner', models.CharField(choices=[('baner_top', 'верхний банер'), ('baner_right', 'правый банер')], default='', help_text='банер', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Article content', verbose_name='Article content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of article when viewing article list on index or news page', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='', verbose_name='Article image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date', verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Article title', max_length=200, verbose_name='Title'),
        ),
    ]
