# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 19:18
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0003_auto_20180115_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='torrent_links',
            new_name='torrent_link',
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='film_genres_autocomplete', blank=True, force_lowercase=True, help_text='Жанры могут включать в себя пробелы', initial='анімэ, баявік, біяграфія, вэстэрн, гістарычны, дакументальны, драма, дэтэктыў, жахі, камедыя, кароткамэтражны, крымінальны, мюзікл, прыгода, серыял, фантастыка', space_delimiter=False, to='KinaKipa.Genre', tree=True),
        ),
    ]
