# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0004_auto_20180108_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='video',
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='', help_text='Краiна', max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='image_url',
            field=models.URLField(blank=True, help_text='Спасылка на карцiнку'),
        ),
        migrations.AddField(
            model_name='film',
            name='video_html',
            field=models.TextField(default='', help_text='html-код для проигрывания видео'),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.CharField(default='', help_text='Працягласць', max_length=25),
        ),
    ]
