# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 21:10
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0004_auto_20180115_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='film_genres_autocomplete', blank=True, force_lowercase=True, help_text='Жанры могут включать в себя пробелы', initial='камедыя, фантастыка, гістарычны, біяграфія, дакументальны, кароткамэтражны, жахі, мюзікл, драма, баявік, прыгода, вэстэрн, дэтэктыў, крымінальны, серыял, анімэ', space_delimiter=False, to='KinaKipa.Genre', tree=True),
        ),
    ]
