# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0005_auto_20180116_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='Назва', max_length=200, unique=True, verbose_name='film_name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='label',
            field=models.CharField(help_text='The name of the tag, without ancestors', max_length=191),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
