# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0006_auto_20180117_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baner',
            old_name='baner',
            new_name='position',
        ),
    ]
