# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 06:40
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0007_auto_20180120_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baner',
            new_name='Banner',
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image/poster'), upload_to='', verbose_name='Малюнак фільма'),
        ),
    ]
