# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0008_auto_20180120_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('index_top', 'верхні на галоўнай'), ('index_right', 'правы на галоўнай')], default='', help_text='position for the banner', max_length=255),
        ),
    ]
