# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0009_auto_20180120_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('index_top', 'верхні на галоўнай'), ('index_right', 'правы на галоўнай')], default='', help_text='пазіцыя банера', max_length=255),
        ),
    ]
