# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 16:58
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0010_auto_20180120_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(default='Content', help_text='Змеціва артыкула', verbose_name='Змеціва артыкула'),
        ),
    ]
