# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0011_auto_20180120_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='news_icon',
            field=models.ImageField(blank=True, help_text='Article news icon', upload_to='', verbose_name='News Icon'),
        ),
        migrations.AddField(
            model_name='article',
            name='news_icon_link',
            field=models.URLField(blank=True, help_text='Link to image for news icon', max_length=500, verbose_name='Link to news icon'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_link',
            field=models.CharField(blank=True, help_text='Link to video. Needs "iframe" tag', max_length=500, verbose_name='Video'),
        ),
    ]
