# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:36
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0013_auto_20180123_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='badge_image',
            field=filebrowser.fields.FileBrowseField(help_text='Article badge image', max_length=500, verbose_name='Badge image'),
        ),
    ]
