# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0014_auto_20180123_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='news_icon_link',
        ),
    ]
