# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 12:35
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0015_remove_article_news_icon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Film poster', max_length=500, null=True, verbose_name='Poster'),
        ),
    ]
