# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 05:11
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import filebrowser.fields
import tagulous.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0016_auto_20180124_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='video_link',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(default='', help_text='Url where banner will lead to', verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='badge_image',
            field=filebrowser.fields.FileBrowseField(help_text='Image for the article that will be used on all list pages', max_length=500, verbose_name='Badge image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(help_text='Змеціва артыкула', verbose_name='Змеціва артыкула'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner consists of image and link', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('index_top', 'верхні на галоўнай'), ('index_right', 'правы на галоўнай')], help_text='On which pages and where this banner will be positioned', max_length=255, verbose_name='Banner position'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Event description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Date and time when the event ends', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Event\\s location', max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Date and time when the event starts', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title', max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, help_text='Country of production', max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=200, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='film_genres_autocomplete', blank=True, force_lowercase=True, help_text='Genres can include spaces. Used like tags.', initial='камедыя, фантастыка, гістарычны, біяграфія, дакументальны, кароткамэтражны, жахі, мюзікл, драма, баявік, прыгода, вэстэрн, дэтэктыў, крымінальны, серыял, анімэ', space_delimiter=False, to='KinaKipa.Genre', tree=True, verbose_name='Movie genres'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Image for the movie that will be used on all list pages', max_length=500, null=True, verbose_name='Выява'),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Film ratings on imdb.com', verbose_name='Imdb rating'),
        ),
        migrations.AlterField(
            model_name='film',
            name='kp_rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Film ratings on kinopoisk.ru', verbose_name='Kinopoisk rating'),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.CharField(blank=True, help_text='Movie length', max_length=30, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='Movie name', max_length=200, unique=True, verbose_name='Movie name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_origin',
            field=models.CharField(blank=True, help_text='Name of the movie in the language of the original', max_length=200, verbose_name='Original movie name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.CharField(blank=True, max_length=800, verbose_name='Actors'),
        ),
        migrations.AlterField(
            model_name='film',
            name='torrent_link',
            field=models.URLField(blank=True, help_text='Torrent link', max_length=2000, verbose_name='Torrent link'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video_html',
            field=models.TextField(blank=True, help_text='html code for displaying the video', verbose_name='Video html code'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(blank=True, help_text='Year of creation', max_length=4, verbose_name='Year'),
        ),
    ]
