# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 11:48
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import filebrowser.fields
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0017_auto_20180125_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='badge_image',
            field=filebrowser.fields.FileBrowseField(help_text='Малюнак артыкула для ўсіх старонак са спісамі артыкулаў', max_length=500, verbose_name='Малюнак плашчака'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Баннер складаецца з малюнка і спасылкі', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='', verbose_name='Малюнак баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('index_top', 'верхні на галоўнай'), ('index_right', 'правы на галоўнай')], help_text='На якой старнке і дзе баннер будзе знаходзіцца', max_length=255, verbose_name='Месцазнаходжанне баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(help_text='Спаслыку куды баннер будзе весці', verbose_name='Спасылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Апісанне мерапрыемства', verbose_name='Апісанне'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Дата і час, калі мерапрыемтсва скончыцца', verbose_name='Час сканчэння мерапрыемства'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Месца правядзення мерапрыемства', max_length=250, verbose_name='Месца'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Дата і час, калі мерапрыемства пачнецца', verbose_name='Час пачатку мерапрыемства'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Назва мерапрыемства', max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, help_text='Краіна вытворчасці', max_length=200, verbose_name='Краіна'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='Апісанне'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=200, verbose_name='Рэжысёр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='film_genres_autocomplete', blank=True, force_lowercase=True, help_text='Жанры могуць уключаць прагалы. Выкарыстоўваюцца як тэгі.', initial='камедыя, фантастыка, гістарычны, біяграфія, дакументальны, кароткамэтражны, жахі, мюзікл, драма, баявік, прыгода, вэстэрн, дэтэктыў, крымінальны, серыял, анімэ', space_delimiter=False, to='KinaKipa.Genre', tree=True, verbose_name='Жанры фільма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Малюнак фільма для ўсіх старонак са спісамі фільмаў', max_length=500, null=True, verbose_name='Малюнак'),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Рэйтынг фільма на imdb.com', verbose_name='Imdb рэйтынг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='kp_rating',
            field=models.FloatField(blank=True, default=0.0, help_text='Рэйтынг фільма на kinopoisk.ru', verbose_name='Рэйтынг Кінапошуку'),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.CharField(blank=True, help_text='Працягласць фільма', max_length=30, verbose_name='Працягласць'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(help_text='Назва фільма', max_length=200, unique=True, verbose_name='Назва фільма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name_origin',
            field=models.CharField(blank=True, help_text='Назва фільма на мове арыгіналу', max_length=200, verbose_name='Арыгінальная назва фільма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.CharField(blank=True, max_length=800, verbose_name='Акцёры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='torrent_link',
            field=models.URLField(blank=True, help_text='Torrent спаслыка', max_length=2000, verbose_name='Torrent спаслыка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video_html',
            field=models.TextField(blank=True, help_text='Html код для адлюстравання відэа', verbose_name='Html код відэа'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(blank=True, help_text='Год вытворчасці', max_length=4, verbose_name='Год'),
        ),
    ]
