# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 13:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0024_delete_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Hero slide image', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='', verbose_name='Hero slide image')),
                ('url', models.URLField(help_text='Url where banner will lead to', verbose_name='Url')),
                ('content', tinymce.models.HTMLField(help_text='Hero slide text', verbose_name='Hero slide text')),
                ('button_caption', models.CharField(help_text='Button caption', max_length=200, verbose_name='Button caption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieHeroSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Hero slide image', null=True, storage=django.core.files.storage.FileSystemStorage(location='layout/image'), upload_to='', verbose_name='Hero slide image')),
                ('url', models.URLField(help_text='Url where banner will lead to', verbose_name='Url')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KinaKipa.Film', verbose_name='Hero movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
