# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0025_heroslide_movieheroslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movieheroslide',
            name='image',
        ),
    ]
