# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 15:24
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0026_auto_20180208_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Banner consists of image and link', max_length=500, null=True, verbose_name='Banner image'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Hero slide image', max_length=500, null=True, verbose_name='Hero slide image'),
        ),
        migrations.AddField(
            model_name='movieheroslide',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Hero slide image', max_length=500, null=True, verbose_name='Hero slide image'),
        ),
    ]
