# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinaKipa', '0027_auto_20180208_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('index_top', 'top on index page'), ('index_right', 'right on index page'), ('article_right', 'right on article page')], help_text='On which pages and where this banner will be positioned', max_length=255, verbose_name='Banner position'),
        ),
    ]
