# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawled_Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва', max_length=200, verbose_name='film_name')),
                ('name_origin', models.CharField(default='', help_text='Назва арыгінала', max_length=200, verbose_name='film_name_origin')),
                ('director', models.CharField(default='', help_text='Рэжысёр', max_length=200)),
                ('year', models.PositiveSmallIntegerField(default=None, help_text='Год')),
                ('kp_rating', models.FloatField(null=True)),
                ('imdb_rating', models.FloatField(null=True)),
                ('genres', models.CharField(default='', help_text='Жанры', max_length=200)),
                ('stars', models.CharField(default='', help_text='Акцёры', max_length=200)),
                ('video_html', models.TextField(default='', help_text='html-код для проигрывания видео')),
                ('length', models.CharField(default='', help_text='Працягласць', max_length=25)),
                ('description', models.TextField(help_text='Апісанне')),
                ('torrent_link', models.URLField(blank=True, help_text='Спасылка на торэнт')),
                ('image_url', models.URLField(blank=True, help_text='Спасылка на карцiнку')),
                ('kp_link', models.URLField(blank=True, help_text='Ссылка на .xml-файл с рейтингом с kp')),
            ],
        ),
    ]
