# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawled_film',
            name='year',
            field=models.CharField(default='', help_text='Год', max_length=4),
        ),
    ]
