# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_auto_20171226_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawled_film',
            name='country',
            field=models.CharField(default='', help_text='Краiна', max_length=200),
        ),
    ]
