# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0003_crawled_film_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_lists', models.URLField(help_text='Страницы, на которых находятся ссылки на фильмы', max_length=2000)),
            ],
        ),
    ]
