# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0004_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawled_film',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Краiна', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Апісанне'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='director',
            field=models.CharField(blank=True, default='', help_text='Рэжысёр', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='genres',
            field=models.CharField(blank=True, default='', help_text='Жанры', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Спасылка на карцiнку'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='kp_link',
            field=models.URLField(blank=True, default='', help_text='Ссылка на .xml-файл с рейтингом с kp'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='kp_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='length',
            field=models.CharField(blank=True, default='', help_text='Працягласць', max_length=30),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='name',
            field=models.CharField(default='', help_text='Назва', max_length=200, verbose_name='film_name'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='name_origin',
            field=models.CharField(blank=True, default='', help_text='Назва арыгінала', max_length=200, verbose_name='film_name_origin'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='stars',
            field=models.CharField(blank=True, default='', help_text='Акцёры', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='torrent_link',
            field=models.URLField(blank=True, default='', help_text='Спасылка на торэнт'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='video_html',
            field=models.TextField(blank=True, default='', help_text='html-код для проигрывания видео'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='year',
            field=models.CharField(blank=True, default='', help_text='Год', max_length=4),
        ),
    ]
