# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0005_auto_20180110_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawled_film',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Краiна', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Апісанне', null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='director',
            field=models.CharField(blank=True, default='', help_text='Рэжысёр', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='genres',
            field=models.CharField(blank=True, default='', help_text='Жанры', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Спасылка на карцiнку', null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='kp_link',
            field=models.URLField(blank=True, default='', help_text='Ссылка на .xml-файл с рейтингом с kp', null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='kp_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='length',
            field=models.CharField(blank=True, default='', help_text='Працягласць', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='name_origin',
            field=models.CharField(blank=True, default='', help_text='Назва арыгінала', max_length=200, null=True, verbose_name='film_name_origin'),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='stars',
            field=models.CharField(blank=True, default='', help_text='Акцёры', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='torrent_link',
            field=models.URLField(blank=True, default='', help_text='Спасылка на торэнт', null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='video_html',
            field=models.TextField(blank=True, default='', help_text='html-код для проигрывания видео', null=True),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='year',
            field=models.CharField(blank=True, default='', help_text='Год', max_length=4, null=True),
        ),
    ]
