# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0007_auto_20180111_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawled_film',
            name='genres',
            field=models.CharField(blank=True, default='', help_text='Жанры', max_length=300),
        ),
        migrations.AlterField(
            model_name='crawled_film',
            name='stars',
            field=models.CharField(blank=True, default='', help_text='Акцёры', max_length=800),
        ),
    ]
