# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0008_auto_20180111_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
