# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0008_auto_20180111_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
